#!/bin/bash

#start postgres
runuser -l postgres --session-command "/usr/pgsql-9.3/bin/pg_ctl init"
runuser -l postgres --session-command "/usr/pgsql-9.3/bin/pg_ctl -D /var/lib/pgsql/9.3/data -l logfile start"

#start redis 
redis-server --daemonize yes

#start jenkins daemon 
if [[ $# -eq 1 ]]; then

  # if `docker run` only has one arguments, we assume user is running alternate command like `bash` to inspect the image
  exec "$@"

else

  # if -tunnel is not provided try env vars
  if [[ "$@" != *"-tunnel "* ]]; then
    if [[ ! -z "$JENKINS_TUNNEL" ]]; then
      TUNNEL="-tunnel $JENKINS_TUNNEL"    
    fi
  fi

  if [[ ! -z "$JENKINS_URL" ]]; then
    URL="-url $JENKINS_URL"
  fi

  exec java $JAVA_OPTS -cp /usr/share/jenkins/slave.jar hudson.remoting.jnlp.Main -headless $TUNNEL $URL "$@"
fi  